In [12]:
import pandas as pd
import pymysql
import numpy as np
import os

In [13]:
a = pd.Series([3, 5, 2, 6])
b = pd.Series(list('oanavsip'),index=[2,4,5,1,7,8,9,23])
print(a>3)
print(b=='a')
print(b[23])

0    False
1     True
2    False
3     True
dtype: bool
2     False
4      True
5     False
1      True
7     False
8     False
9     False
23    False
dtype: bool
p

In [14]:
db = pymysql.connect(host='localhost',user='root',password='root',db='mysql')
sql = "select * from user"
a = pd.read_sql(sql,db)
print(a)

        Host           User Select_priv Insert_priv Update_priv Delete_priv  \
0  localhost           root           Y           Y           Y           Y
1  localhost  mysql.session           N           N           N           N
2  localhost      mysql.sys           N           N           N           N

  Create_priv Drop_priv Reload_priv Shutdown_priv  ... max_questions  \
0           Y         Y           Y             Y  ...             0
1           N         N           N             N  ...             0
2           N         N           N             N  ...             0

  max_updates max_connections max_user_connections                 plugin  \
0           0               0                    0  mysql_native_password
1           0               0                    0  mysql_native_password
2           0               0                    0  mysql_native_password

                       authentication_string password_expired  \
0  *81F5E21E35407D884A6CD4A731AEBFB6AF209E1B                N
1  *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE                N
2  *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE                N

  password_last_changed password_lifetime account_locked
0   2021-06-28 12:56:48              None              N
1   2021-06-28 12:56:48              None              Y
2   2021-06-28 12:56:48              None              Y

[3 rows x 45 columns]

In [15]:
df = pd.read_csv('D:\Code\VSCode_Python\data\心心享洗-自助洗车订单 .csv')
# excel1 = pd.read_excel('D:\Code\VSCode_Python\豆瓣电影Top250.xls')

# print(df['实付金额']>5)
print(df['支付渠道'].value_counts())
# print(df.groupby(['实付金额'],sort=False)['订单ID'].count()) #实付金额？的订单ID有？个,不进行排序

余额支付    920
微信支付      1
Name: 支付渠道, dtype: int64

In [16]:
#df[(约束条件)][实际要查询的行列]
# print(df[ ( (df["实付金额"] > 5) & (df["实付金额"] < 10) )]['实付金额']) 
print(df[ ( (df["实付金额"] > 5) & (df["实付金额"] < 10) | (df["实付金额"]==0) )]['实付金额'])

print(df[( df["实付金额"]==df["订单金额"] )][['订单金额','实付金额']])

0      9.65
2      0.00
3      0.00
4      0.00
7      5.99
       ...
914    0.00
915    0.00
916    6.00
918    0.00
919    0.00
Name: 实付金额, Length: 355, dtype: float64
     订单金额  实付金额
0    9.65  9.65
1    2.49  2.49
2    0.00  0.00
3    0.00  0.00
4    0.00  0.00
..    ...   ...
916  6.00  6.00
917  1.00  1.00
918  0.00  0.00
919  0.00  0.00
920  0.28  0.28

[843 rows x 2 columns]

In [17]:
# df.head(15)
# df.loc[5:10,["设备ID","订单ID"]]
# df.loc[5:20]
df[ (df["实付金额"]!=df["订单金额"]) ].loc[:200] #在200行范围内，使用布尔表达式查询

,订单ID,用户手机号(假号码),设备ID,订单金额,实付金额,支付渠道,订单状态,订单时间
6,1283201558544392192',18681932356,157829830668829372',9.98,3.98,余额支付,订单成功,7/15/2020 08:47:47
10,1282841699336593408',15086345752,157829830668829372',6.95,0.95,余额支付,订单成功,7/14/2020 08:57:50
21,1281898398789935104',13873634825,157829841525951628',6.39,0.39,余额支付,订单成功,7/11/2020 18:29:29
23,1281896190249803776',15086345752,157829818607994096',5.43,0.00,余额支付,订单成功,7/11/2020 18:20:43
32,1280075267104317440',13578935613,157829818607994096',13.35,7.35,余额支付,订单成功,7/6/2020 17:45:01
35,1279745553877704704',15086345752,157829841525951628',6.99,0.99,余额支付,订单成功,7/5/2020 19:54:51
37,1279295712659775488',19102916999,157829841525951628',11.07,5.07,余额支付,订单成功,7/4/2020 14:07:21
38,1279245111838121984',19102916999,157829830668829372',22.53,16.53,余额支付,订单成功,7/4/2020 10:46:17
40,1278897595284201472',15072847004,157829841525951628',11.76,5.76,余额支付,订单成功,7/3/2020 11:45:22
41,1278652700980158464',18705330606,157829841525951628',5.81,0.00,余额支付,订单成功,7/2/2020 19:32:15
42,1278652155343151104',18667897087,157829830668829372',5.99,0.00,余额支付,订单成功,7/2/2020 19:30:05
45,1278527191000555520',15981918823,157829810475321301',7.16,1.16,余额支付,订单成功,7/2/2020 11:13:31
46,1278474297769467904',13578935613,157829841525951628',8.30,2.30,余额支付,订单成功,7/2/2020 07:43:20
129,1272767473707524096',18081947479,157829841525951628',6.00,0.00,余额支付,订单成功,6/16/2020 13:46:27
135,1592118280439289c5aw9y',13579801449,157829830668829372',8.28,2.28,余额支付,订单成功,6/14/2020 15:04:40
137,1592116205602287ve0k44',13578935613,157829841525951628',12.18,6.18,余额支付,订单成功,6/14/2020 14:30:05
190,159178088392223416vm1r',19102916999,157829810475321301',5.26,0.00,余额支付,订单成功,6/10/2020 17:21:23
196,1591517041617228rnyl3k',18581921234,157829818607994096',6.29,0.29,余额支付,订单成功,6/7/2020 16:04:01

In [18]:
# df.sort_values(by=["设备ID","实付金额"],ascending=[False,True]) 

print(df.groupby(["设备ID"],sort=False).count().sort_values(by=["实付金额"],ascending=[False])["订单ID"] )

#已设备id作为分组字段，统计平均订单金额。按平均金额逆排序

df.groupby(by=["设备ID"],sort=False).mean().sort_values( by = ["订单金额"], ascending=[False])[["订单金额"]]

设备ID
157829841525951628'    284
157829830668829372'    267
157829810475321301'    232
157829818607994096'    138
Name: 订单ID, dtype: int64

                         订单金额
设备ID
157829830668829372'  3.657416
157829810475321301'  3.308319
157829841525951628'  3.191937
157829818607994096'  2.672101

In [19]:
df.groupby(by=["设备ID"],sort=False).agg(["mean","min","max","sum","median","mad","var","std"])

                       用户手机号(假号码)                                           \
                             mean          min          max            sum
设备ID
157829830668829372'  1.665283e+10  13210804617  19981846223  4446306361831
157829841525951628'  1.649527e+10  13009034401  19973006840  4684655511833
157829818607994096'  1.653535e+10  13100028229  19973006840  2281878187019
157829810475321301'  1.692914e+10  13054078994  19981846223  3927561451792

                                                                      \
                           median           mad                  var
设备ID
157829830668829372'  1.804963e+10  2.234052e+09  5428794805270381568
157829841525951628'  1.662408e+10  2.269974e+09  5645383834724734976
157829818607994096'  1.770987e+10  2.204254e+09  5346619904819385344
157829810475321301'  1.817324e+10  2.056286e+09  4833180054551667712

                                       订单金额       ...                       \
                              std      mean  min  ...        var       std
设备ID                                              ...
157829830668829372'  2.329977e+09  3.657416  0.0  ...  12.299832  3.507112
157829841525951628'  2.376002e+09  3.191937  0.0  ...  10.226734  3.197926
157829818607994096'  2.312276e+09  2.672101  0.0  ...  11.114808  3.333888
157829810475321301'  2.198449e+09  3.308319  0.0  ...  12.609618  3.551002

                         实付金额                                                  \
                         mean  min    max     sum median       mad        var
设备ID
157829830668829372'  3.159775  0.0  18.47  843.66  2.280  2.620117  11.293094
157829841525951628'  2.645845  0.0  12.64  751.42  1.610  2.365636   7.985795
157829818607994096'  2.228043  0.0  16.31  307.47  0.915  2.249247   9.100817
157829810475321301'  2.920991  0.0  21.52  677.67  1.980  2.537498  11.551657


                          std
设备ID
157829830668829372'  3.360520
157829841525951628'  2.825915
157829818607994096'  3.016756
157829810475321301'  3.398773

[4 rows x 24 columns]

In [23]:
dict1 = { 'c1':{1:23,2:31,3:54},
       'c2':{3:57,9:92,5:94},
       'c3':{} }
a = pd.DataFrame(dict1)

# axis{1：列统计，0：行统计}

# print(a.isnull().any(axis=0))
print(a[a.isnull().any(axis=1)])
# 删除缺失值
print(a.dropna(how='all',axis=1))

     c1    c2
1  23.0   NaN
2  31.0   NaN
9   NaN  92.0
5   NaN  94.0
     c1    c2
1  23.0   NaN
2  31.0   NaN
3  54.0  57.0
9   NaN  92.0
5   NaN  94.0